#dbとwebのコンテナを作る
version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testPass
      - POSTGRES_DB=devDB
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: #.をmountさせる
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db