#dbとwebのコンテナを作る
version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testPass
      - POSTGRES_DB=devDB
  web:
    build: . #Refers to Dockerfile
    #command: bundle install
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate RAILS_ENV=development && bundle exec rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: #.をmountさせる
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true